export { default as Email } from './Email/Email'
export { default as Fullname } from './Fullname/Fullname'
export { default as Password } from './Password/Password'
export { default as Phone } from './Phone/Phone'
export { default as Role } from './Role/Role'
