export { default as Halls } from './Halls/Halls'
export { default as Map } from './Map/Map'
export { default as Main } from './Main/Main'
export { default as Menus } from './Menus/Menus'
export { default as Offer } from './Offer/Offer'
