export { default as Comment } from './Comment/Comment'
export { default as Contacts } from './Contacts/Contacts'
export { default as MainGroup } from './MainGroup/MainGroup'
export { default as RelatedRestaurants } from './RelatedRestaurants/RelatedRestaurants'
export { default as Shedule } from './Shedule/Shedule'
export { default as Whatsapp } from './Whatsapp/Whatsapp'
