export { default as AuthPage } from './AuthPage/AuthPage'
export { default as AdminPage } from './AdminPage/AdminPage'
export { default as EditObjectPage } from './EditObjectPage'
export { default as EditRestaurantPage } from './EditRestaurantPage'
export { default as EditUserPage } from './EditUserPage'
